version: '3.7'

services:
  # docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3
    rabbitmq:
      image: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - 5672:5672
    redis:
      image: redis
      ports:
        - 6379:6379
    esserver:
      image: elasticsearch
      port: 19200:9200
    tikaserver:
      image: apache/tika
      port: 8888:9998


    # docker-compose build
    # docker-compose up
    # -d detach (tak perlu pantau terus)

    # docker-compose logs
    # see log inside

    # docker-compose down
    # stop

